/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package com.yassar.client_2101082047;

import com.yassar.client_2101082047.controller.AnggotaController;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author LENOVO
 */
public class FormAnggota extends javax.swing.JFrame {
    
  

    /**
     * Creates new FormAnggota
     */
    AnggotaController controller;
    public FormAnggota() {
        initComponents();
        controller = new AnggotaController(this);
        controller.bersihForm();
        controller.viewTabel();
    }
    
    public JTable getTableAnggota() {
        return tableAnggota;
    }

    public JTextField getTxtAlamat() {
        return txtAlamat;
    }

    public JTextField getTxtIdAnggota() {
        return txtIdAnggota;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
